### ISSUE TITLE
Update not triggering with event listener on hoc

### ISSUE THREAD

**Issue by donnysim** [vueComponent/jsx#32]
jsx: 1.0.0-beta.3
vue: 3.0.0-beta.23

```jsx
import { h, Transition } from 'vue';

function MyTransition(props, ctx) {
  return h(Transition, ctx.slots.default);
}

setup() {
  const isOpen = ref(false);
  setInterval(() => { isOpen.value = !isOpen.value }, 1000);

  return () => <MyTransition>{isOpen.value && <h1>Visible</h1>}</MyTransition>;
}
```

does not seem to trigger an update on `isOpen` change. Converting it to an `h` function:
```jsx
return () => h(MyTransition, isOpen.value ? <h1>Visible</h1> : null);
// or recommended
return () => h(MyTransition, () => isOpen.value ? <h1>Visible</h1> : null);
```
works fine though. I tried converting functional component to a normal component but the problem persists.

**Comment by donnysim** [comment]
It seems it uses `createVNode`, which does not work in this case I guess?

**Comment by Amour1688** [comment]
```jsx
import {
  ref, Transition, createApp, defineComponent,
} from 'vue';

const MyTransition = (_, { slots }) => (
  <Transition>{slots.default()}</Transition>
);

const App = defineComponent({
  setup() {
    const isOpen = ref(false);
    setInterval(() => { isOpen.value = !isOpen.value; }, 1000);
    return () => <MyTransition>{isOpen.value && <h1>Visible</h1>}</MyTransition>;
  },
});
```

It works.

try 

```
const MyTransition = (_, { slots }) => (
  <Transition>{slots.default()}</Transition>
);
```

**Comment by donnysim** [comment]
It seems it does not have anything to do with a hoc, I made a reproduction [codesandbox](https://codesandbox.io/s/objective-elbakyan-qy5xc) blue text is vue `h`, red text (which does not work) is jsx. Main code is in /src/Toggle.vue.

**Comment by donnysim** [comment]
I'll just close this until I get what is going on, sorry for wasting your time 😓

**Comment by Amour1688** [comment]
> I'll just close this until I get what is going on, sorry for wasting your time 😓

It's fine. Thanks for your issue.

**Comment by donnysim** [comment]
Ok, so I found the culprit, if you have an event listener, it stops updating with jsx version (or when using plain `createVNode` instead of `h`). Same repo [codesandbox](https://codesandbox.io/s/objective-elbakyan-qy5xc?file=/src/Toggle.vue)

**Comment by Amour1688** [comment]
#33

**Comment by donnysim** [comment]
Seems to work with the fix 👍

**Comment by Amour1688** [comment]
v1.0.0-beta.4
