### ISSUE TITLE
support v-html 

### ISSUE THREAD

**Issue by uinio** [vueComponent/jsx#40]

**Comment by xmsz** [comment]
什么时候支持？
还有domPropsInnerHTML

**Comment by Amour1688** [comment]
> 什么时候支持？
> 还有domPropsInnerHTML

本周末

**Comment by Amour1688** [comment]
> 什么时候支持？
> 还有domPropsInnerHTML

`domPropsInnerHTML` https://github.com/vuejs/vue-next/issues/1810
