### ISSUE TITLE
支持isCustomElement属性

### ISSUE THREAD

**Issue by xmsz** [vueComponent/jsx#43]
isCustomElement只能在编译环境进行配置

**Comment by Amour1688** [comment]
问题能描述清楚点吗

**Comment by xmsz** [comment]
> 问题能描述清楚点吗
需求/背景
- 有一些自定义组件，例如'wx-view'，运行时会提示「Failed to resolve component」
- 官方回答[Unable get rid of web component warning
](https://github.com/vuejs/vue-next/issues/1414)，解决办法是在编译阶段配置vue-loader选项
- 项目用的jsx，所以不知道在哪配置

**Comment by Amour1688** [comment]
https://github.com/vueComponent/jsx/pull/42/commits/a8710f86b489521f851d357239901948e038593c
