### ISSUE TITLE
 JSX element type 'List' does not have any construct or call signatures.

### ISSUE THREAD

**Issue by zdz4510** [vueComponent/jsx#49]
上级组件：
import { defineComponent, ref, reactive } from "vue";
import  List from  "@/components/List";
const Home = defineComponent(() => {

  const list = ref([
    5
  ]);
  const flag = ref(
    false
  );

  const list2 = reactive([
    2, 3, 4, 5, 6
  ])
  console.log(list);
  const handleClick = () => {
    list2[2] = 1003;
  }
  const handleClick2 = () => {
    list2[2] = -10000;
  }
  return () => (
    <>
      // 使用list组件
       <List  />
      {
        list.value.map((item) =>
          <h1 onClick={handleClick} class="bg">{item}</h1>
        )
      }
      {
        flag.value ? <p onClick={handleClick2}>true</p> : <p onClick={handleClick2} >false</p>
      }

      {
        list2.map((item) =>
          <h1>{item}</h1>
        )
      }
    </>
  );
})
export default Home;

// list 组件
import { onMounted, ref } from "vue";
const List = {
  setup() {
    const num = ref(0);
    onMounted(() => {
        console.log('aaa')
    });
    return () => <div>{num.value}</div>

  
}
}
  
export default  List;

**Comment by Amour1688** [comment]
你的 `List` 里面没有返回 DOM

**Comment by zdz4510** [comment]
list中retuan改为<div>{num.value}</div>依然报错

**Comment by zdz4510** [comment]
复制的代码中未显示div,在list组件中设置了retuan（）=>{<div>{num.value}</div>}

**Comment by zdz4510** [comment]
复制的代码中未显示div,在list组件中设置了return（）=>{

{num.value}
}
