### ISSUE TITLE
.vue 文件中使用 jsx, style 的 scoped 不起作用

### ISSUE THREAD

**Issue by BoltDoggy** [vueComponent/jsx#51]
style 的 scoped 生成的 data-v-xxxx, jsx 生成的为 data-v-xxxx-s

![image](https://user-images.githubusercontent.com/2586280/89140933-a12a1100-d575-11ea-9a8e-d3870b89f356.png)

![image](https://user-images.githubusercontent.com/2586280/89140900-8b1c5080-d575-11ea-8166-b6f1e7ea48b6.png)

===

自己尝试看了一下源码, 没有解决的, 目前猜想是, jsx 的 vnode 丢失了 scopeId 属性, 导致 vue3 的 runtime 把 jsx 的 dom 当做了 slot.

因为 template 中执行了这个方法, 使得 vnode 获取了 scopeId

![image](https://user-images.githubusercontent.com/2586280/89141121-362d0a00-d576-11ea-9b2a-a679800e2a86.png)

![image](https://user-images.githubusercontent.com/2586280/89141110-2dd4cf00-d576-11ea-9174-a30eff8c8b75.png)

**Comment by Amour1688** [comment]
在 Vue 2 中 JSX 也是不支持 scoped css 的。使用 JSX 的话，建议使用 `CSS-IN-JS` 的方案

**Comment by BoltDoggy** [comment]
> 在 Vue 2 中 JSX 也是不支持 scoped css 的。使用 JSX 的话，建议使用 `CSS-IN-JS` 的方案

jsx 既然能生成 data-v-xxxx-s, 说明至少是可行的吧.

**Comment by BoltDoggy** [comment]
https://forum.vuejs.org/t/jsx-with-scoped-styles-possible/7523 社区中肯定是有一些人喜欢 jsx + scoped css 的. 虽然 Vue 2 一直没有人实现, 但我认为是值得尝试的.

**Comment by Amour1688** [comment]
https://github.com/vuejs/vue-next/blob/b10bc2820a742859fc52fac3bd8e2ad41e3678ed/packages/compiler-sfc/src/stylePluginScoped.ts#L81-L92

`::v-slotted(.foo) -> .foo[xxxxxxx-s]`

**Comment by Ttou** [comment]
不生效就是因为 `scopedId` 少了一个 `-s`
![iShot2020-08-04下午01 43 46](https://user-images.githubusercontent.com/4298437/89257358-94cab480-d658-11ea-8317-abfbe4fa485d.png)

**Comment by Mikeccx** [comment]
// this may did work
import { defineComponent, computed, ref, getCurrentInstance, withScopeId } from 'vue'
export default defineComponent({
    setup() {
        const instance = getCurrentInstance()
        const scopeId = instance.type.__scopeId
        const withId = withScopeId(scopeId)
        return withId( () => (
            <div class="page-wraper">
       )
}

**Comment by Arman19941113** [comment]
> // this may do work
> import { defineComponent, computed, ref, getCurrentInstance, withScopeId } from 'vue'
> export default defineComponent({
> setup() {
> const instance = getCurrentInstance()
> const scopeId = instance.type.__scopeId
> const withId = withScopeId(scopeId)
> return withId( () => ( <div class="page-wraper">)
> }

This works indeed. But not elegant. Is there any way to support this feature more graceful.

**Comment by xialvjun** [comment]
@yyx990803 Will you plan to support scoped css in vue SFC written with jsx/tsx ?

In current status, it seems almost support it. Vue3 renders `<div class="aaa" data-v-05d27cca-s=""></div>` and the inject style is `.aaa[data-v-05d27cca]`. I don't know why it add a `-s` after.

**Comment by xialvjun** [comment]
> 在 Vue 2 中 JSX 也是不支持 scoped css 的。使用 JSX 的话，建议使用 `CSS-IN-JS` 的方案。
> 
> 但是 JSX 也不应该生成 scopeId。

**Vue 2 中是支持的**：

```vue
<template></template>
<script lang="tsx">
import { h, defineComponent, ref } from "@vue/composition-api";
export default defineComponent({
  setup: (props, ctx) => {
    const count = ref(0);
    const increase = () => count.value++;
    return () => <div class="huge_size" onClick={increase}>{count.value}</div>
  }
});
</script>
<style lang="less" scoped>
.huge_size {
  font-size: 96px;
}
</style>
```

```js
// babel.config.js
module.exports = {
  presets: [["@vue/jsx"], ["@vue/app", { jsx: { injectH: false } }]],
};
```

```json
// tsconfig.json
{
  "compilerOptions": {
    "jsx": "preserve",
  },
}
```

**Comment by xialvjun** [comment]
@BoltDoggy 就像题主截图的一样，jsx 生成的 DOM 的属性，莫名其妙多了个 `-s`，怀疑是哪处转换的 bug。

> style 的 scoped 生成的 data-v-xxxx, jsx 生成的为 data-v-xxxx-s
> 
> ![image](https://user-images.githubusercontent.com/2586280/89140933-a12a1100-d575-11ea-9a8e-d3870b89f356.png)
> 
> ![image](https://user-images.githubusercontent.com/2586280/89140900-8b1c5080-d575-11ea-8166-b6f1e7ea48b6.png)
>

**Comment by sendking** [comment]
有个疑问，就是每个文件里去引 withScopeId 不觉得累么
